# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2PG8F2eo6OzzxO2nUYb46QiVSlgR-wB
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import numpy as np

# Placeholder predict function
def predict(features):
    # In a real application, this would load a trained model and make a prediction.
    # For demonstration, a simple rule-based prediction for Iris classification:
    sepal_l, sepal_w, petal_l, petal_w = features[0]

    if petal_l < 2.0:
        return ["Setosa"]
    elif petal_l < 5.0 and petal_w < 1.7:
        return ["Versicolor"]
    else:
        return ["Virginica"]

st.title('Classifying Iris Flowers')
st.markdown('Toy model to play to classify iris flowers into \
(setosa, versicolor, virginica) based on their sepal/petal \
and length/width.')

st.header("Plant Features")
col1, col2 = st.columns(2)

with col1:
    st.text("Sepal characteristics")
    sepal_l = st.slider('Sepal lenght (cm)', 1.0, 8.0, 0.5)
    sepal_w = st.slider('Sepal width (cm)', 2.0, 4.4, 0.5)

with col2:
    st.text("Pepal characteristics")
    petal_l = st.slider('Petal lenght (cm)', 1.0, 7.0, 0.5)
    petal_w = st.slider('Petal width (cm)', 0.1, 2.5, 0.5)

st.text('')
if st.button("Predict type of Iris"):
    result = predict(
        np.array([[sepal_l, sepal_w, petal_l, petal_w]]))
    st.text(result[0])

st.text('')
st.text('')
st.markdown(
    # Baris terakhir di gambar terpotong, biasanya berisi credit atau link
    ""
)

